In [30]:
import pandas as pd
import numpy as np

data=pd.read_csv("IPcountry_CCcountry_mismatch_0107-0608.csv")
print data.head(5)
print data['cc_country'][0]
print data.iloc[1], type(data.iloc[1])
print data[1:3]

   account_id country_code cc_country ll_country  \
0    14787564          NaN         US         JP
1    15317587           NG         US         NG
2    16453029           PE         US         PE
3    16453029          NaN         US         PE
4    16453029          NaN         US         PE

                                 bank_name  amount_usd      email      id
0  JCB INTERNATIONAL CREDIT CARD CO., LTD.    8.389611  gmail.com     NaN
1                                      NaN   82.140000  gmail.com  553646
2                                      NaN   36.110000  gmail.com     NaN
3                                      NaN    3.370000  gmail.com     NaN
4                                      NaN   12.240000  gmail.com     NaN
US
account_id       15317587
country_code           NG
cc_country             US
ll_country             NG
bank_name             NaN
amount_usd          82.14
email           gmail.com
id                 553646
Name: 1, dtype: object <class 'pandas.core.series.Series'>
   account_id country_code cc_country ll_country bank_name  amount_usd  \
1    15317587           NG         US         NG       NaN       82.14
2    16453029           PE         US         PE       NaN       36.11

       email      id
1  gmail.com  553646
2  gmail.com     NaN

In [75]:
from collections import defaultdict
def cc_ll_pattern_risk(data):
    group={}
    patterns=[]
    columnsd=data.columns
    print columnsd
    for i in range(len(data)):
        #print i
        #print data[i]
        #print data['ll_country'][i]
        pattern=data['cc_country'][i]+'_'+str(data['ll_country'][i])
        if pattern not in patterns:
            patterns.append(pattern)
        if pattern not in group:
            group[pattern]=pd.DataFrame(columns=columnsd)
        #print len(group[pattern])
        group[pattern].loc[len(group[pattern])]=data.iloc[i]
    #print group[pattern]
    risks={}
    for pattern in patterns:
        table=group[pattern]
        #print pattern
        # print table, type(table)
        
        risk=float(pd.Series.count(table['id']))/float(len(table))
        table['cc_ll_risk']=risk
        group[pattern]=table
        risks[pattern]=risk
    return group, risks
    


group,risks=cc_ll_pattern_risk(data) 
print group['US_PE']
#['cc_ll_risk']
#print risks
risks=pd.Series(risks)
print risks

Index([u'account_id', u'country_code', u'cc_country', u'll_country',
       u'bank_name', u'amount_usd', u'email', u'id'],
      dtype='object')
    account_id country_code cc_country ll_country  \
0     16453029           PE         US         PE
1     16453029          NaN         US         PE
2     16453029          NaN         US         PE
3     16453029          NaN         US         PE
4     16453029          NaN         US         PE
5     16108846          NaN         US         PE
6     16108846          NaN         US         PE
7     16108846          NaN         US         PE
8     15707291           PE         US         PE
9     16231936           PE         US         PE
10    16231936          NaN         US         PE

                      bank_name  amount_usd                  email  id  \
0                           NaN       36.11              gmail.com NaN
1                           NaN        3.37              gmail.com NaN
2                           NaN       12.24              gmail.com NaN
3                           NaN      364.83              gmail.com NaN
4                           NaN        1.47              gmail.com NaN
5       FIA CARD SERVICES, N.A.        1.32              gmail.com NaN
6       FIA CARD SERVICES, N.A.       10.48              gmail.com NaN
7       FIA CARD SERVICES, N.A.        5.42              gmail.com NaN
8             CREDIT UNION WEST        0.25              gmail.com NaN
9   WESTPAC BANKING CORPORATION       30.99  monarchennovation.com NaN
10  WESTPAC BANKING CORPORATION        3.37  monarchennovation.com NaN

    cc_ll_risk
0            0
1            0
2            0
3            0
4            0
5            0
6            0
7            0
8            0
9            0
10           0
AE_AF     0.000000
AE_DK     0.000000
AE_EG     0.000000
AE_GB     0.000000
AE_HK     0.000000
AE_IN     0.100000
AE_IQ     0.000000
AE_IT     0.833333
AE_JP     0.000000
AE_LB     0.000000
AE_MY     0.000000
AE_NL     0.000000
AE_OM     0.000000
AE_PK     0.000000
AE_QA     0.000000
AE_RO     0.250000
AE_SA     0.000000
AE_TR     0.000000
AE_US     0.000000
AL_GR     0.000000
AL_TR     0.000000
AM_LT     1.000000
AM_US     0.000000
AR_AG     1.000000
AR_AU     0.000000
AR_BR     0.000000
AR_CA     0.000000
AR_GB     0.000000
AR_IT     0.000000
AR_MA     1.000000
            ...
VG_TT     1.000000
VI_AI     0.000000
VN_DE     0.000000
VN_FI     0.000000
VN_IN     0.000000
VN_KR     0.000000
VN_PK     0.000000
VN_SG     0.000000
VN_TH     0.000000
VN_TW     0.000000
VN_US     0.000000
ZA_AO     0.000000
ZA_BW     0.000000
ZA_CA     1.000000
ZA_CR     0.000000
ZA_DE     0.000000
ZA_GB     0.000000
ZA_IN     0.000000
ZA_KW     0.000000
ZA_MZ     0.500000
ZA_NZ     0.000000
ZA_QA     0.000000
ZA_RU     0.000000
ZA_TH     0.000000
ZA_TR     0.000000
ZA_US     0.500000
ZA_ZM     0.000000
ZA_nan    0.000000
ZW_ZA     0.000000
ZW_ZM     1.000000
dtype: float64

In [80]:
risks1=risks[risks>0.5]
#print risks1
risks2=risks1[risks<1.0]
print risks2
risks2=risks2.sort(axis=0,ascending=False)
print risks2

AE_IT    0.833333
AU_AE    0.666667
AU_DE    0.857143
AU_ID    0.666667
AU_JO    0.666667
AU_PH    0.950000
AU_UA    0.750000
BR_RU    0.800000
BZ_HR    0.666667
CA_US    0.541436
CH_GB    0.750000
DE_RO    0.571429
DK_ES    0.714286
DK_GB    0.666667
ES_US    0.666667
GB_BA    0.666667
GB_MA    0.600000
GI_GB    0.666667
IE_ES    0.666667
IE_SA    0.800000
IL_CA    0.666667
IN_EG    0.833333
IT_DE    0.555556
IT_MA    0.727273
MT_DE    0.750000
NG_DE    0.571429
PK_US    0.700000
PL_NL    0.666667
PL_TH    0.600000
RO_DE    0.666667
RU_DE    0.825000
RU_FR    0.935484
RU_NL    0.923077
RU_RO    0.750000
RU_US    0.850000
TH_FR    0.750000
US_AE    0.566667
US_BD    0.636364
US_BG    0.970588
US_ID    0.806452
US_IQ    0.600000
US_MA    0.700000
US_PK    0.696203
US_RO    0.592593
US_RU    0.612903
US_SG    0.571429
US_UA    0.565217
dtype: float64
None

In [ ]:
def cc_ll_pattern_risk(data):
    group={}
    patterns=[]
    columnsd=data.columns
    print columnsd
    for i in range(len(data)):
        #print i
        #print data[i]
        #print data['ll_country'][i]
        pattern=data['cc_country'][i]+'_'+str(data['ll_country'][i])
        if pattern not in patterns:
            patterns.append(pattern)
        if pattern not in group:
            group[pattern]=pd.DataFrame(columns=columnsd)
        #print len(group[pattern])
        group[pattern].loc[len(group[pattern])]=data.iloc[i]
    #print group[pattern]
    risks={}
    for pattern in patterns:
        table=group[pattern]
        #print pattern
        # print table, type(table)
        
        risk=float(pd.Series.count(table['id']))/float(len(table))
        table['cc_ll_risk']=risk
        group[pattern]=table
        risks[pattern]=risk
    return group, risks